#docker compose --> Explore the compose file reference --> compose file
networks:
  #expense is the network name
  expense: {} 
volumes:
  # mysql is volume name
  mysql: 
services:
  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: mysql:1.0.0
    networks: 
    - expense
    #docker compose --> Explore the compose file reference --> Compose Specification repository --> 05-services.md --> ctl F --> container name
    container_name: mysql 
    # docker hub --> explore --> mysql --> ctl F --> -v
    volumes:
    - mysql:/var/lib/mysql 

  backend:
    image: backend:1.0.0
    networks:
    - expense
    container_name: backend
    # volumes are not required because it is stateless
    depends_on:
    - mysql

  frontend:
    image: frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    # volumes are not required because it is stateless
    ports:
    - 80:80
    depends_on:
    - backend

